### ISSUE TITLE
CAM RuntimeError: shape '[1, 3, 13, 13, 10]' is invalid for input of size 92055

### ISSUE THREAD

**Issue by LvShuaiChao** [IDayday/YOLOv4_CAM#1]
![image](https://user-images.githubusercontent.com/35528109/147387587-e6f7597b-ea50-453e-9b67-f10ab1c0ce0e.png)
博主您好，我的YOLO v4模型可以跑通，但是在进行可视化的时候，一直报RuntimeError: shape '[1, 3, 13, 13, 10]' is invalid for input of size 92055的resize错误，不知道这种情况应该如何修改代码呢？

**Comment by IDayday** [comment]
> ![image](https://user-images.githubusercontent.com/35528109/147387587-e6f7597b-ea50-453e-9b67-f10ab1c0ce0e.png)
> 
> 博主您好，我的YOLO v4模型可以跑通，但是在进行可视化的时候，一直报RuntimeError: shape '[1, 3, 13, 13, 10]' is invalid for input of size 92055的resize错误，不知道这种情况应该如何修改代码呢？
> 
> 
> 
> 
> 
> 
> 
> 

根据报错信息，是你的输入不能reshape成（1，3，13，13，10），应该检查你的类别设置
